version: '3.3'
services:
  redis-master:
    image: 'bitnami/redis:5.0.5'
    # ports:
    #   - '6379'
    environment:
      - REDIS_REPLICATION_MODE=master
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - redis-data:/bitnami/redis/data
    networks:
      - lan
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == worker
  redis-replica:
    image: 'bitnami/redis:5.0.5'
    # ports:
    #   - '6379'
    depends_on:
      - redis-master
    environment:
      - REDIS_REPLICATION_MODE=slave
      - REDIS_MASTER_HOST=redis-master
      - REDIS_MASTER_PORT_NUMBER=6379
      - ALLOW_EMPTY_PASSWORD=yes
    networks:
      - lan
    volumes:
      - redis-data:/bitnami/redis/data
    deploy:
      mode: replicated
      replicas: 2
      placement:
        constraints:
          - node.role == worker
  redis-sentinel:
    image: 'bitnami/redis-sentinel:5.0.5'
    environment:
      - REDIS_MASTER_HOST=tasks.redis-master
      - REDIS_MASTER_SET=masterset
      - ALLOW_EMPTY_PASSWORD=yes
    # ports:
    #   - '26379:26379'
    networks:
      - lan
    deploy:
      mode: replicated
      replicas: 3
      placement:
        constraints:
          - node.role == worker
networks:
  lan:
    external: true
volumes:
  redis-data:
